### ISSUE TITLE
Communicate f-value back to caller?

### ISSUE THREAD

**Issue by anriseth** [JuliaNLSolvers/LineSearches.jl#10]
The linesearches communicates the step length back to the caller, but not the objective value. 
We should pass the objective value back as well to stop unnecessary calls of the objective function in `Optim` and ~~`NLOpt`~~ `NLSolve`

**Comment by cortner** [comment]
But see [Optim.jl #288](https://github.com/JuliaOpt/Optim.jl/issues/282)

**Comment by anriseth** [comment]
If some version of what's discussed there is implemented, I guess this will be automatically sorted.
Currently, Optim is passing the newest information to linesearches via the LineSearchResults, but does not use the result when updating f_x. I think this line could be changed to use
the latest information in `state.lsr`: 
https://github.com/JuliaOpt/Optim.jl/blob/11c935e3689ce05e8ef75ea30fff7f592a26f56d/src/optimize.jl#L195

**Comment by cortner** [comment]
I agree

**Comment by cortner** [comment]
note that some line searches will also have gradient information that should also be communicated back.

**Comment by anriseth** [comment]
Hopefully this can be sorted out after JuliaOpt/Optim.jl#337

**Comment by pkofod** [comment]
This can be closed now, right?

**Comment by anriseth** [comment]
> This can be closed now, right?

Yep, should be fixed with #37
