### ISSUE TITLE
Add logging functionality

### ISSUE THREAD

**Issue by anriseth** [JuliaNLSolvers/LineSearches.jl#102]
I'd like to see a flexible logging / tracing functionality here. 

Currently there is little info provided when things go wrong inside the linesearches. Finiteness tests such as #101 should (optionally) warn the user that something is wrong.

**Comment by pkofod** [comment]
Yes, but let’s see if we can’t make something a bit more elegant than optim

**Comment by anriseth** [comment]
> let’s see if we can’t

I hope we *can* ;)

**Comment by timholy** [comment]
See #177
