### ISSUE TITLE
Have the same required arguments for all the LineSearches

### ISSUE THREAD

**Issue by anriseth** [JuliaNLSolvers/LineSearches.jl#117]
@antoine-levitt has suggested that we require all the line search algorithms to have the same required arguments. 
```jl
(ls::LineSearch)(ϕ, dϕ, ϕdϕ,alpha0::T, ϕ_0, dϕ_0) where T
```

That way, we don't need a `perform_linesearch` wrapper like the one I added to the custom optimizer example.

**Comment by pkofod** [comment]
Suggested where? I agree though.

**Comment by anriseth** [comment]
Suggested on the Optim gitter channel ;)

**Comment by anriseth** [comment]
Closed via #121
