### ISSUE TITLE
Wrong object returned in _hzI12

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaNLSolvers/LineSearches.jl#123]
```
        if iterfinite >= iterfinitemax
            return T(0), true
            #             error("Failed to achieve finite test value; alphatest = ", alphatest)
        end
```
at initialguess.jl:234 returns Float64, Bool, where it should return Float64. Not sure what the right fix is here, so passing it to @pkofod ;-)

**Comment by anriseth** [comment]
I'm guessing (on my phone) that the Boolean is supposed to be passed to `mayterminate`. I'll try to fix it later today (just need to finish fixing typos in my thesis)

**Comment by pkofod** [comment]
That's a mistake I think, and I think @anriseth is correct.
