### ISSUE TITLE
Support DoubleFloats

### ISSUE THREAD

**Issue by anriseth** [JuliaNLSolvers/LineSearches.jl#130]
Currently these don't work together with the `Inf` values in our `@with_kw` structs. 

This can be fixed with https://github.com/JuliaMath/DoubleFloats.jl/issues/18, and if so we should re-enable the DoubleFloats tests in `arbitrary_precision.jl`. Otherwise, we'll have to think of something new here

**Comment by pkofod** [comment]
Can this be closed @anriseth ?
