### ISSUE TITLE
Initial HagerZhang: norm(gr) -> norm(gr)^2

### ISSUE THREAD

**Issue by mohamed82008** [JuliaNLSolvers/LineSearches.jl#133]
https://github.com/JuliaNLSolvers/LineSearches.jl/blob/1f40bf319887b77f66f89154763b5d49924894a7/src/initialguess.jl#L292

In the paper, the divisor is `norm(gr)^2`

**Comment by mohamed82008** [comment]
Should also check against `alphamax`.

**Comment by pkofod** [comment]
Happy to accept bug fixes

**Comment by pkofod** [comment]
In general a if you can provid a line number and an equation number from the paper or line in the reference implementation (wherever you checked) review will be much faster. Thanks

**Comment by mohamed82008** [comment]
Oh my bad sorry. This is from initialization step I0-b page 12.

**Comment by pkofod** [comment]
> Oh my bad sorry.

I hope you didn't read it in an annoyed voice, I just wanted to say that it's much more likely that I can quickly reply if I have both line numbers (as you provided!) and equation numbers :) (got to remember those smileys ;) )
