### ISSUE TITLE
Concerns about Hager Zhang initialization

### ISSUE THREAD

**Issue by mohamed82008** [JuliaNLSolvers/LineSearches.jl#134]
I have a few questions/concerns about the initialization of HagerZhang:
1. If we start at or close to the minimizer, `dphi0` will be close to 0, so it is possible this will error https://github.com/JuliaNLSolvers/LineSearches.jl/blob/1f40bf319887b77f66f89154763b5d49924894a7/src/initialguess.jl#L252.
2. In the paper, the quadratic stepping is optional and when it fails, the algorithm falls back on using an initial guess that is a multiple of the previous step size. Isn't this a more reasonable thing to do rather than error above?
3. If I understand correctly, this line https://github.com/JuliaNLSolvers/LineSearches.jl/blob/1f40bf319887b77f66f89154763b5d49924894a7/src/initialguess.jl#L266 is not in the original paper.
4. While I understand the rationale behind the while loop in https://github.com/JuliaNLSolvers/LineSearches.jl/blob/1f40bf319887b77f66f89154763b5d49924894a7/src/initialguess.jl#L228 which was used to ensure that `phitest` is finite, possibly a concern with log-barrier methods, but this guarantee is gone in https://github.com/JuliaNLSolvers/LineSearches.jl/blob/1f40bf319887b77f66f89154763b5d49924894a7/src/initialguess.jl#L268. Maybe do a similar loop here?

**Comment by mohamed82008** [comment]
Suggestions:
1. Remove the error and fallback on the next branch.
2. Check that `phitest` is finite at the end.
3. Make QuadStep an optional parameter.

Beside the fixes proposed in https://github.com/JuliaNLSolvers/LineSearches.jl/issues/133. If you approve, a PR will be next.

**Comment by mohamed82008** [comment]
Another place where starting close to convergence may cause a problem https://github.com/JuliaNLSolvers/LineSearches.jl/blob/1f40bf319887b77f66f89154763b5d49924894a7/src/hagerzhang.jl#L119.

**Comment by pkofod** [comment]
I have been aware about the staring close to a solution for a while, but never fixed it. A pr is very much welcome

**Comment by pkofod** [comment]
This is brilliant, thanks. I think they will give fewer issues that relate to weird line search errors on well-behaved problems in the future!
