### ISSUE TITLE
Bump NaNMath

### ISSUE THREAD

**Issue by GregPlowman** [JuliaNLSolvers/LineSearches.jl#158]
Is it possible to bump `NaNMath` to version 1 ?

**Comment by sethaxen** [comment]
Also it seems CompatHelper has been deactivated, or it would have opened a PR to do so.

**Comment by rasmushenningsson** [comment]
bump :slightly_smiling_face:

**Comment by pkofod** [comment]
Sorry sorry sorry... I'll do it

**Comment by rasmushenningsson** [comment]
Thank you!
