### ISSUE TITLE
Would an AbstractLineSearchType be a good idea?

### ISSUE THREAD

**Issue by kellertuer** [JuliaNLSolvers/LineSearches.jl#171]
I am using `LineSearches` in one of my packages – and just to be able to write something generic an abstract linesearch type for all linesearch structs would be great. Is this something that others find helpful as well? Then I think I could do a PR.

**Comment by pkofod** [comment]
You mean in another package? It would mean that different packages would have to follow a common API? Or did you mean for the line searches in this package?

**Comment by kellertuer** [comment]
Maybe a bit of both.
For now Manopt.jl has its own line searched but also an extension to use the ones from here, cf https://github.com/JuliaManifolds/Manopt.jl/blob/master/ext/ManoptLineSearchesExt.jl and our wrapper type https://github.com/JuliaManifolds/Manopt.jl/blob/master/src/helpers/LineSearchesTypes.jl

So with a generic API here, that wrapper might be a bit nicer, but with a `LineSearchesBase.jl` API like package, I could maybe even remodel my line searches to fit such an API as well.

**Comment by kellertuer** [comment]
But we can also just stick to the wrapper for now, maybe.
