### ISSUE TITLE
Simple example doesn't work

### ISSUE THREAD

**Issue by Goysa2** [JuliaNLSolvers/LineSearches.jl#44]
Hi,

I am trying to do the simple example provided, but it doesn't work.

`using Optim`
`using LineSearches`
`prob = Optim.UnconstrainedProblems.examples["Rosenbrock"]`

all works fine but when I do 
`algo_hz = Newton(linesearch = hagerzhang!)`

I get the following error: 
WARNING: both LineSearches and Optim export "hagerzhang!"; uses of it in module Main must be qualified
ERROR: UndefVarError: hagerzhang! not defined

Why is that? 

Thanks for your help!

**Comment by Goysa2** [comment]
I have Optim 0.7.8 and LineSearches 0.1.5 
Your solution works thanks!

**Comment by anriseth** [comment]
Okay, that's good.

Just as a heads up: There are some major and breaking changes in Optim 1.0 and the corresponding LineSearches versions. So if your code suddenly stops working after the future update, have a look at the Optim page, or get in touch with us ;)
