### ISSUE TITLE
Remove gradient storage array from linesearches?

### ISSUE THREAD

**Issue by anriseth** [JuliaNLSolvers/LineSearches.jl#47]
All the linesearches take an argument `g::Array` or similar, which was previously used to store the gradient. With the use of NLSolversBase and `*gradient!`, this seems unnecessary?

I'll remove it, if nobody has an objection @cortner @pkofod

**Comment by cortner** [comment]
I agree.

**Comment by cortner** [comment]
Incidentally, the current master of LineSearches and Optim have so many nice improvements, what is the time-line for tagging them?

**Comment by pkofod** [comment]
Remove it!

> Incidentally, the current master of LineSearches and Optim have so many nice improvements, what is the time-line for tagging them?

I intend to tag v1.0.0 Optim very soon.

**Comment by cortner** [comment]
wonderful

**Comment by anriseth** [comment]
What are we thinking for versioning in LineSearches? It seems to me that #43 with its deprecations works well at the current major version, whilst this change should require a major update?

**Comment by pkofod** [comment]
> What are we thinking for versioning in LineSearches? It seems to me that #43 with its deprecations works well at the current major version, whilst this change should require a major update?

That sort of depends. Can you just allow the old version, throw a warning, and then just make sure the behavior is still correct?

**Comment by anriseth** [comment]
> That sort of depends. Can you just allow the old version, throw a warning, and then just make sure the behavior is still correct?

Yes, I believe that is what https://github.com/JuliaNLSolvers/LineSearches.jl/blob/master/src/deprecate.jl#L16 is doing?

**Comment by pkofod** [comment]
> Yes, I believe that is what https://github.com/JuliaNLSolvers/LineSearches.jl/blob/master/src/deprecate.jl#L16 is doing?

Hmm, maybe I'm misunderstanding you. If the change is made in such a way that it is not breaking (old code would still work), you don't need a major version bump.

**Comment by anriseth** [comment]
> Hmm, maybe I'm misunderstanding you. If the change is made in such a way
that it is not breaking (old code would still work), you don't need a major
version bump.

Great. So we should do a minor version bump to tag the changes made in #43.
But the change I proposed in this issue (removing the gradient storage) is
breaking, so requires a major bump (and technically means we can remove the
deprecations introduced in #43)
