### ISSUE TITLE
Remove deprecations

### ISSUE THREAD

**Issue by anriseth** [JuliaNLSolvers/LineSearches.jl#60]
Deprecations on types and g-storage were introduced in LineSearches v2. We're now on v3, so it's time to remove them.

**Comment by pkofod** [comment]
Fixed right ?

**Comment by anriseth** [comment]
Ah, yes (y)

**Comment by pkofod** [comment]
> (y)

this isn't facebook ;)

**Comment by anriseth** [comment]
Haha, too many chatting platforms to deal with. I'll just write everything in LaTeX from now on.

**Comment by pkofod** [comment]
```LaTeX
\documentclass[preview,border=12pt,varwidth]{standalone}
\usepackage{tikz}
\def\checkmark{\tikz\fill[scale=0.4](0,.35) -- (.25,0) -- (1,.7) -- (.25,.15) -- cycle;} 
\begin{document}
\checkmark
\end{document}
```

**Comment by anriseth** [comment]
Hahaha, yes! That's so much clearer
