### ISSUE TITLE
Do we need LineSearchResults?

### ISSUE THREAD

**Issue by anriseth** [JuliaNLSolvers/LineSearches.jl#79]
Optim doesn't really use LineSearchResults for much, and neither does LineSearches. Maybe we should just get rid of it?

One con that I can think of.
1. LineSearchResults works sort-of like the `store_trace` does in Optim, and may be valuable (if we bother using it)

If we move on with this remake, we should also fully embrace `value_gradient!` etc. from NLSolversBase. This must somehow be done in conjunction with a way to communicate the slope of the function `\phi(\alpha) = f(x + \alpha * s)`, which now is calculated using `vecdot(s, gradient(f))`. So maybe this is the time to fully move onwards and redefine to work with `phi(\alpha)` instead of `f` and `gradient(f)`?

**Comment by pkofod** [comment]
I think this is the closest issue we have that covers simplifying the interface. Let's get rid of LSR and work with `phi(alpha)` and `phi'(alpha)` instead. From Optim (or maybe through a special optimization object here in LineSearches) we can then pass `phi` and `phi'` functions that of course use `value_gradient!` to avoid repeated calculations.

What stands in the way of this? Would it ruin the interpolation schemes? We don't want to introduce further calculations here.

cc @cortner @antoine-levitt
