### ISSUE TITLE
LineSearchOptions

### ISSUE THREAD

**Issue by cortner** [JuliaNLSolvers/LineSearches.jl#9]
At the moment all linesearchoptions (e.g. C1, C2) are passed via arguments. This makes it a bit of a pain for the user to set those arguments given how the line search functions are passed to Optim. I suggest to either move to a `LineSearchOptions` type or to keyword arguments.

**Comment by anriseth** [comment]
I agree. Pros and cons of keyword arguments vs a `LineSearchOptions` type?

Keywords is the easiest change to make. Will `LineSearchOptions` give us more power + flexibility than plain kwargs, or potentially be less messy?

**Comment by cortner** [comment]
Another option would be to make a linesearch a type that stores the options, the function `linesearch!` would then dispatch to the correct linesearch. 

I actually like this by far the best.

**Comment by cortner** [comment]
```
optimise!(f, g!, method=LBFGS(), 
                         linesearch=BackTracking(interp=:cubic, rho=0.9))
```

**Comment by cortner** [comment]
@pkofod what do you think about this; I think it will make the Optim codes much cleaner.

**Comment by anriseth** [comment]
Sorry, I think I didn't register the two lasts posts when you wrote them.
Something along this line with linesearch and alphaguess types/routines sound like a good idea for flexibility.

**Comment by pkofod** [comment]
Yes, I think we need something like this. I'll think, and return.

**Comment by cortner** [comment]
I am still offering to help, but (like you) I just had another child born so any work I can do on this will be sporadic at best for the next few months

**Comment by pkofod** [comment]
> I am still offering to help, but (like you) I just had another child born so any work I can do on this will be sporadic at best for the next few months

Congrats! Hope you're all doing great. I think we're pretty close to being at a point where we should have a stab at this, right @anriseth ? I say we go the dispatch route. It will be the easiest way for the user to flexibly specify how to perform the line search (just like without `Optimizer` types in Optim).

**Comment by anriseth** [comment]
Yes, the dispatch route is great.
Would it make sense to start this after implementing the *Function changes in NLBase? Or would you say we can start this in parallel? (I'm thinking in terms of merging issues on top of existing PRs)

**Comment by pkofod** [comment]
> Yes, the dispatch route is great.
> Would it make sense to start this after implementing the *Function changes in NLBase? Or would you say we can start this in parallel? (I'm thinking in terms of merging issues on top of existing PRs)

Sure, we can wait. The `perform_linesearch` PR originates from the *Differentiable-PR, but I have been trying to merge stuff that does not directly relate to that PR in separate PRs, such that it is less of a mess!

**Comment by cortner** [comment]
is there any work in this direction yet?

**Comment by anriseth** [comment]
@cortner I have not done any work on this. Maybe @pkofod has?

**Comment by pkofod** [comment]
No work here yet, but let's have a stab at it. I think I prefer just a single element representing the line search. Something like
```
optimise(f, g!, method = LBFGS(BackTracking(interp=:cubic, rho=0.9, MyAlphaGuess()))
```
That might look a bit compressed, buy you can always do
```
alphaguess = ...
linesearch = ...(..., alphaguess)
optimise!(f, g!, method = LBFGS(linesearch = linesearch))
```

**Comment by cortner** [comment]
As a first step, I just want to switch from functions to types; I just got annoyed by it again so will have a stab at it. I've actually already tested it locally. I need to combine it with a very small PR for Optim only. Hopefully I can get it done today.

**Comment by pkofod** [comment]
Go for it! If you get time to complete it, it can be included before I tag v1.0.0 on Optim (which would make a whole lot of sense as well!).

**Comment by pkofod** [comment]
this was resolved when moving to types right?

**Comment by cortner** [comment]
should be - yes.

**Comment by pkofod** [comment]
thanks for working on this @cortner !
